### ISSUE TITLE
Use of :author_id instead of :id

### ISSUE THREAD

**Issue by robert-laws** [learn-co-curriculum/modification-nested-routes-reading#10]
Shouldn't the correct URI Pattern within the section *CREATING A NEW POST FOR AN AUTHOR* be slightly different?

**Existing Text**
This gives us access to ``/authors/:id/posts/new``, and a ``new_author_post_path`` helper.

**Suggested Text**
This gives us access to ``/authors/:author_id/posts/new``, and a ``new_author_post_path`` helper.

**Comment by cjbrock** [comment]
Hi @robert-laws! This is actually a question of developer style here. As you get further into your career, you'll find that you developer your own style of writing code, much like a prose writing style. If someone asked both of use to write the story of the Three Little Pigs, it would probably be semantically the same, but the details would be different. Sometimes the pigs are brothers, sometimes they're cousins, sometimes they're doing laundry, sometimes they're making soup...you get the idea. There are many different ways to get to the same helper, as you've obviously figured out, and the nice thing about being a developer is that you get to choose which one you like and which one feels the best to you. 
// Corinna
