### ISSUE TITLE
Fixnum and Bignum deprecated (huge error too tall to get to the top of easily)

### ISSUE THREAD

**Issue by bhollan** [learn-co-curriculum/modification-nested-routes-reading#11]
Steps to recreate:
Clone lab as-is.
Delete the `.sqlite` files.
Run `rake db:migrate`.

As can be demonstrated by [this commit](https://github.com/ylhoony/modification-nested-routes-reading-v-000/commit/51834380c424dfdfccb100638903651396e42075) from a student.

This is caused by `Fixnum` and `Bignum` being unified in Ruby 2.4.X under the banner `Integer` and the fix implemented is [documented here](https://stackoverflow.com/questions/41504106/ruby-2-4-and-rails-4-stack-level-too-deep-systemstackerror).

**Comment by curiositypaths** [comment]
Hi there,

Until we migrate to Rails v5 (planned for the second quarter fo 2018) the recommended version of Ruby is 2.3.6.

As always thank you for contributing!
