### ISSUE TITLE
Update for Rails 5?

### ISSUE THREAD

**Issue by robert-laws** [learn-co-curriculum/modification-nested-routes-reading#13]
Hello, I was working on this example in my own IDE, which makes use of Rails 5.1.5. It seems that for this version of rails, the way to use the form_for method is different than in Rails 4. I was able to successfully create a database entry for a nested form with the following code.

```ruby
<%= form_for([@post.author, @post]) do |f| %>
  <label>Post title:</label><br>
 
  <%= f.hidden_field :author_id %>
 
  <%= f.text_field :title %><br>
  <label>Post Description</label><br>
  <%= f.text_area :description %><br>
  <%= f.submit %>
<% end %>
```

Also, with Rails 5, I had to specify the :create route in my nested routes to get it to process the POST request properly, as shown below:

```ruby
resources :authors, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create]
  end
```

Not sure if the examples will be updated for Rails 5 or not?

**Comment by curiositypaths** [comment]
Hi there,

Thank you for the recommendation. We expect to update the curriculum to Rails v5 during the second quarter of 2018.

As always thank you for contributing.
