### ISSUE TITLE
Completed but not updating

### ISSUE THREAD

**Issue by malbazaz** [learn-co-curriculum/modification-nested-routes-reading#14]
I completed the readme but it is not showing that I have completed it.

**Comment by cjbrock** [comment]
Hi @malbazaz! If you're having issues with the Learn platform, you don't want to file an Github issue. Github issues are generally for issues with the curriculum itself (say, we're teaching something incorrectly, or something is broken). If your lights aren't working, then hop on Ask A Question, and one of the Technical Coaches should be able to help you out!
// Corinna
