### ISSUE TITLE
Need another resources: line in code-along snippet

### ISSUE THREAD

**Issue by AudreyJones** [learn-co-curriculum/modification-nested-routes-reading#15]
Instead of:
# config/routes.rb
resources :authors, only: [:show, :index] do
  resources :posts, only: [:show, :index, :new]
end

Need an additional line:
# config/routes.rb
resources :authors, only: [:show, :index] do
  resources :posts, only: [:show, :index, :new]
end
resources :posts

to make the new form for authors/:id/posts/new work in-browser

**Comment by helloamandamurphy** [comment]
Thanks for sharing this! I was having the same issue and that fixed it!

**Comment by Nanton83** [comment]
Thanks!

**Comment by schanrai** [comment]
This worked for me too but I cannot find where the reference to post_path is coming from in the posts#new action and view - why does it error out?

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
