### ISSUE TITLE
PostsContoller update method

### ISSUE THREAD

**Issue by PineappleGuy** [learn-co-curriculum/modification-nested-routes-reading#18]
In the section in the read me titled "Editing An Author's Posts", the last line reads "Pretty easy, right? **We didn't even have to change the controller this time.** What's the catch?". This is incorrect. The update method at this point in the code-along is this:

1  def update
2   @post = Post.find(params[:id])
3   @post.update(**params.require(:post)**)
4    redirect_to post_path(@post)
5  end

line 3 causes an "**ActiveModel::ForbiddenAttributesError**" error and needs to be changed to this:

@post.update(**post_params**)

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
