### ISSUE TITLE
Does not update 

### ISSUE THREAD

**Issue by FigueroaR** [learn-co-curriculum/modification-nested-routes-reading#21]
ActiveModel::ForbiddenAttributesError

def update
  #binding.pry
    @post = Post.find(params[:id])
    @post.update(params.require(:post))   <<<<<<< get stuck here, does not catch pry either
    redirect_to post_path(@post)
end

## Request
Parameters:

{"utf8"=>"✓",
 "_method"=>"patch",
 "authenticity_token"=>"cN+DFWHivpjQoYf0XtmRS0ognyTWok6O9IoYhEHBYx+mgcRYwYXTqCrqOaVQIogJPaPATFLjh7WPQoHhy+9ogA==",
 "post"=>{"author_id"=>"10", "title"=>"Good Music", "description"=>"what is dat?!?!?"},
 "commit"=>"Update Post",
 "id"=>"26"}

Response
Headers:

None

![Capture](https://user-images.githubusercontent.com/48839893/71492973-5b4fe200-2809-11ea-8a7c-9684b5252083.JPG)

**Comment by Sdcrouse** [comment]
I checked the solution branch; that line of code needs to be changed to `@post.update(post_params)`. I'll send a PR for it.

**Comment by Sdcrouse** [comment]
They merged in my changes, so I think this issue can be closed now.

**Comment by lizbur10** [comment]
Hello,

Thank you for submitting this PR and for contributing to a learn-co-curriculum repository!

We appreciate your support! 💙
