### ISSUE TITLE
LAB IS IN WRONG ORDER

### ISSUE THREAD

**Issue by scottibe** [learn-co-curriculum/modification-nested-routes-reading#9]
THIS README BELONGS BEFORE THE PREVIOUS LAB. COME ON!

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙

**Comment by Marie-Burns22** [comment]
Hi,  I think this lab is still in the wrong order. If this lab had been before the previous lab it would have saved me about 2-3 hours of time struggling with the conditionals.  Super frustrating to spend half of a day struggling with something and then go through this lab and have it explained clearly.

I think other students would appreciate this readme before the previous lab.
Thanks!
